services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./
    container_name: backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "1337:1337"
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}

  frontend:
    build:
      context: ./web
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      PUBLIC_BACKEND_URL: http://backend:1337

volumes:
  mysql_data:
